### ISSUE TITLE
Activies do not seems to be saved to the database

### ISSUE THREAD

**Issue by Hont91** [Lysferd/potential-ironman#43]
For some reason, while an Activity is created with no trouble, and redirects to the #show page just like it's supposed to, after going back to the Commission, the Activity is nowhere to be found, it also does not appear on the full activities list, as if it was never saved to the database.

**Comment by Hont91** [comment]
While trying to understand this bug, through the use of byebug, it was discovered that the Activity was actually saved into the database, as when creating a new one the id was 8, instead of the expected 1, the question is why are the activities not being show.

**Comment by Lysferd** [comment]
I'm checking this up.
